package arrays;

import java.util.Locale;

import static net.lh.util.Print.print;

/**
 * @author lh
 * Write a method taht creates and initializes a
 * two-dimensional array of double.The size of
 * the array is determined by the arguemnts of
 * the method. and the initialization values are
 * a range determined by beginning and ending
 * values that are also argument of the method.
 * Create a second method that will print the
 * array generated by the first method. In main()
 * test the methods by creating and printing
 * several different sizes of arrays.
 **/
public class E03_TwoDDoubleArray {
    public static double[][] twoDDoubleArray(int xLen, int yLen, double valStart, double valEnd) {
        double[][] array = new double[xLen][yLen];
        double increment = (valEnd - valStart) / (xLen * yLen);
        double val = valStart;
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array[i].length; j++) {
                val += increment;
                array[i][j] = val;
            }
        }
        return array;
    }

    public static void printArray(double[][] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array[i].length; j++) {
                System.out.printf(Locale.US, "%.18f ", array[i][j]);
            }
            print();
        }
    }

    public static void main(String[] args) {
        double[][] twoD = twoDDoubleArray(4, 6, 47.0, 99.0);
        printArray(twoD);
        print("**********");
        double[][] twoD2 = twoDDoubleArray(2, 2, 47.0, 99.0);
        printArray(twoD2);
        print("**********");
        double[][] twoD3 = twoDDoubleArray(9, 5, 47.0, 99.0);
        printArray(twoD3);
    }
}
